from django.urls import path, re_path

from . import views

app_name = 'monitoring'

urlpatterns = [
    path(
        'api/v1/monitoring/device/',
        views.monitoring_device_list,
        name='api_monitoring_device_list',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/$',
        views.device_metric,
        name='api_device_metric',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/nearby-devices/$',
        views.monitoring_nearby_device_list,
        name='api_monitoring_nearby_device_list',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/dpi_summary_v2/$',
        views.device_metric,
        name='api_device_metric_dpi',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/dpi_client_summary/$',
        views.device_metric,
        name='api_device_metric_client_summary',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/real_traffic/$',
        views.device_metric,
        name='api_device_metric_real_traffic',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/tsipreport/$',
        views.device_metric,
        name='api_device_metric_tsipreport',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/wan_status/$',
        views.device_metric,
        name='api_device_metric_wan_status',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/ipsectunnel_list/$',
        views.device_metric,
        name='api_device_metric_ipsectunnel_list',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/configpush/$',
        views.device_metric,
        name='api_device_metric_configpush',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/interface_list/$',
        views.device_metric,
        name='api_device_metric_interface_list',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/interface_event/$',
        views.device_metric,
        name='api_device_metric_interface_event',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/interface_traffic/$',
        views.device_metric,
        name='api_device_metric_interface_traffic',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/lat_qua_report/$',
        views.device_metric,
        name='api_device_metric_lat_qua_report',
    ),
    re_path(
        r'^api/v1/monitoring/device/(?P<pk>[^/]+)/timeseries/$',
        views.device_metric,
        name='api_device_metric_timeseries',
    ),
    path(
        'api/v1/monitoring/geojson/',
        views.monitoring_geojson_location_list,
        name='api_location_geojson',
    ),
    re_path(
        r'^api/v1/monitoring/location/(?P<pk>[^/]+)/device/$',
        views.monitoring_location_device_list,
        name='api_location_device_list',
    ),
    path(
        'api/v1/monitoring/wifi-session/',
        views.wifi_session_list,
        name='api_wifi_session_list',
    ),
    re_path(
        r'^api/v1/monitoring/wifi-session/(?P<pk>[^/]+)/$',
        views.wifi_session_detail,
        name='api_wifi_session_detail',
    ),
]
