# Generated by Django 4.2.17 on 2025-05-17 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.NEXAPP_USERS_ORGANIZATION_MODEL),
        ('nexapp_radius', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nas',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.NEXAPP_USERS_ORGANIZATION_MODEL, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='radius_settings', to=settings.NEXAPP_USERS_ORGANIZATION_MODEL, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.NEXAPP_USERS_ORGANIZATION_MODEL, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='radiusbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.NEXAPP_USERS_ORGANIZATION_MODEL, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='radiuscheck',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.NEXAPP_USERS_ORGANIZATION_MODEL, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='radiusgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.NEXAPP_USERS_ORGANIZATION_MODEL, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='radiuspostauth',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.NEXAPP_USERS_ORGANIZATION_MODEL, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='radiusreply',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.NEXAPP_USERS_ORGANIZATION_MODEL, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='radiustoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.NEXAPP_USERS_ORGANIZATION_MODEL, verbose_name='organization'),
        ),
    ]
