# Generated by Django 4.2.17 on 2025-04-30 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.CONFIG_TEMPLATE_MODEL),
        migrations.swappable_dependency(settings.CONFIG_CONFIG_MODEL),
        ('nexapp_users', '0020_populate_password_updated_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tunnel', max_length=128)),
                ('vpn_type', models.CharField(choices=[('ipsec', 'IPsec'), ('wireguard', 'WireGuard'), ('openvpn', 'OpenVPN'), ('vxlan', 'VXLAN')], max_length=20)),
                ('mode', models.CharField(choices=[('site_to_site', 'Site-to-Site'), ('hub_spoke', 'Hub & Spoke'), ('full_mesh', 'Full Mesh')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('error', 'Error')], default='pending', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_config_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Toggle to enable/disable this tunnel')),
                ('local_identifier', models.CharField(default='@tun3.local', max_length=64)),
                ('remote_identifier', models.CharField(default='@tun3.remote', max_length=64)),
                ('ike_version', models.CharField(choices=[('ikev', 'IKEV1 & IKEV2'), ('ikev1', 'IKEv1'), ('ikev2', 'IKEv2')], default='ike', max_length=6)),
                ('ike_encryption_algorithm', models.CharField(choices=[('aes128', 'AES-128'), ('aes192', 'AES-192'), ('aes256', 'AES-256'), ('3des', '3DES'), ('des', 'DES')], default='aes128', max_length=7)),
                ('ike_integrity_algorithm', models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA-1'), ('sha256', 'SHA-256'), ('sha384', 'SHA-384'), ('sha512', 'SHA-512'), ('aescmac', 'AES-CMAC'), ('aesxcbc', 'AES-XCBC')], default='sha256', max_length=15)),
                ('ike_diffie_hellman_group', models.CharField(choices=[('modp1024', 'MODP-1024'), ('modp1536', 'MODP-1536'), ('modp2048', 'MODP-2048'), ('modp3072', 'MODP-3072'), ('modp4096', 'MODP-4096')], default='modp2048', max_length=12)),
                ('ike_key_lifetime', models.PositiveIntegerField(default=3600, help_text='Lifetime in seconds')),
                ('esp_version', models.CharField(choices=[('esp', 'ESP'), ('espv1', 'ESPv1'), ('espv2', 'ESPv2')], default='esp', max_length=6)),
                ('esp_encryption_algorithm', models.CharField(choices=[('aes128', 'AES-128'), ('aes192', 'AES-192'), ('aes256', 'AES-256'), ('3des', '3DES'), ('des', 'DES')], default='aes128', max_length=7)),
                ('esp_integrity_algorithm', models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA-1'), ('sha256', 'SHA-256'), ('sha384', 'SHA-384'), ('sha512', 'SHA-512'), ('aescmac', 'AES-CMAC'), ('aesxcbc', 'AES-XCBC')], default='sha256', max_length=15)),
                ('esp_diffie_hellman_group', models.CharField(choices=[('modp1024', 'MODP-1024'), ('modp1536', 'MODP-1536'), ('modp2048', 'MODP-2048'), ('modp3072', 'MODP-3072'), ('modp4096', 'MODP-4096')], default='modp2048', max_length=12)),
                ('esp_key_lifetime', models.PositiveIntegerField(default=3600, help_text='Lifetime in seconds')),
                ('device_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_device_a', to=settings.CONFIG_CONFIG_MODEL)),
                ('device_b', models.ManyToManyField(blank=True, related_name='as_device_b', to=settings.CONFIG_CONFIG_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openwisp_users.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.CONFIG_TEMPLATE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevicePeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_ip', models.GenericIPAddressField(help_text='Management IP of local device')),
                ('peer_ip', models.GenericIPAddressField(help_text='Management IP of peer device')),
                ('link_subnet', models.CharField(help_text='Subnet for link', max_length=64)),
                ('local_role', models.CharField(choices=[('hub', 'Hub'), ('spoke', 'Spoke')], max_length=16)),
                ('peer_role', models.CharField(choices=[('hub', 'Hub'), ('spoke', 'Spoke')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_peers', to=settings.CONFIG_CONFIG_MODEL)),
                ('peer_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_peers', to=settings.CONFIG_CONFIG_MODEL)),
                ('tunnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_peers', to='sdwan_tunnel.tunnel')),
            ],
            options={
                'verbose_name': 'Device Peer',
                'verbose_name_plural': 'Device Peers',
            },
        ),
        migrations.CreateModel(
            name='ConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('config_text', models.TextField(blank=True, null=True)),
                ('action', models.CharField(help_text='push, delete or rollback', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openwisp_users.organizationuser')),
                ('tunnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_histories', to='sdwan_tunnel.tunnel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Config History',
                'verbose_name_plural': 'Config Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('topology_id', models.IntegerField()),
                ('devices', models.JSONField(help_text='List of OpenWISP Device IDs')),
                ('details', models.JSONField(blank=True, help_text='Additional event context', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TunnelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField()),
                ('latency_ms', models.FloatField(null=True)),
                ('jitter_ms', models.FloatField(null=True)),
                ('packet_loss_percent', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tunnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='sdwan_tunnel.tunnel')),
            ],
            options={
                'verbose_name': 'Tunnel Status',
                'verbose_name_plural': 'Tunnel Statuses',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tunnel', 'timestamp'], name='sdwan_tunne_tunnel__d85e2e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tunnel',
            constraint=models.UniqueConstraint(fields=('device_a', 'name'), name='unique_tunnel_per_device_a'),
        ),
        migrations.AlterUniqueTogether(
            name='devicepeer',
            unique_together={('tunnel', 'local_device', 'peer_device')},
        ),
    ]
