# Generated by Django 4.2.17 on 2025-04-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan_tunnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='pre_shared_key',
            field=models.CharField(blank=True, help_text='Persisted IPsec pre-shared key', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='subnet',
            field=models.CharField(blank=True, help_text='Allocated link subnet for this tunnel', max_length=64, null=True),
        ),
    ]
