# Generated by Django 4.2.17 on 2025-05-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan_tunnel', '0002_tunnel_pre_shared_key_tunnel_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='device_a_subnet',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='device_a_wan_ip',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
