# Generated by Django 4.2.17 on 2025-05-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan_tunnel', '0003_tunnel_device_a_subnet_tunnel_device_a_wan_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='device_b_subnet',
            field=models.CharField(blank=True, help_text='Allocated Subnet for this tunnel', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='device_b_wan_ip',
            field=models.CharField(blank=True, help_text='Allocated IP for this tunnel', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='device_a_subnet',
            field=models.CharField(blank=True, help_text='Allocated Subnet for this tunnel', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='device_a_wan_ip',
            field=models.CharField(blank=True, help_text='Allocated wan IP for this tunnel', max_length=128, null=True),
        ),
    ]
