# Generated by Django 4.2.17 on 2025-05-03 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CONFIG_CONFIG_MODEL),
        ('sdwan_tunnel', '0006_tunnel_dpdaction_tunnel_ipcomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='device_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_device_a', to=settings.CONFIG_CONFIG_MODEL),
        ),
    ]
