# Generated by Django 4.2.17 on 2025-05-03 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CONFIG_CONFIG_MODEL),
        ('sdwan_tunnel', '0007_alter_tunnel_device_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tunnel',
            name='dpdaction',
        ),
        migrations.RemoveField(
            model_name='tunnel',
            name='ipcomp',
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='device_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_device_a', to=settings.CONFIG_CONFIG_MODEL),
        ),
    ]
