# Generated by Django 4.2.17 on 2025-05-14 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan_tunnel', '0009_tunnel_dpdaction_tunnel_ipcomp_alter_tunnel_device_a'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confighistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='confighistory',
            old_name='payload_hash',
            new_name='config_hash',
        ),
        migrations.RenameField(
            model_name='confighistory',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='confighistory',
            name='config_text',
        ),
        migrations.RemoveField(
            model_name='confighistory',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='confighistory',
            name='triggered_by',
        ),
        migrations.RemoveField(
            model_name='confighistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='confighistory',
            name='action',
            field=models.CharField(choices=[('push', 'push'), ('delete', 'delete'), ('rollback', 'rollback')], help_text='push, delete or rollback', max_length=20),
        ),
        migrations.AlterField(
            model_name='confighistory',
            name='payload',
            field=models.JSONField(help_text='The list of API payload calls'),
        ),
        migrations.AlterField(
            model_name='confighistory',
            name='tunnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdwan_tunnel.tunnel'),
        ),
    ]
