# Generated by Django 4.2.17 on 2025-05-17 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.NEXAPP_USERS_ORGANIZATION_MODEL),
        ('sdwan_tunnel', '0012_alter_tunnel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.NEXAPP_USERS_ORGANIZATION_MODEL),
        ),
    ]
