# Generated by Django 4.2.17 on 2025-06-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan_tunnel', '0013_alter_tunnel_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='forceencaps',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='ike_version',
            field=models.CharField(choices=[('ike', 'IKEV1 & IKEV2'), ('ikev1', 'IKEv1'), ('ikev2', 'IKEv2')], default='ike', max_length=6),
        ),
    ]
