# Generated by Django 4.2.17 on 2025-06-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan_tunnel', '0014_tunnel_forceencaps_alter_tunnel_ike_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tunnel',
            name='forceencaps',
        ),
    ]
