# Generated by Django 4.2.17 on 2025-06-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan_tunnel', '0015_remove_tunnel_forceencaps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tunnel',
            name='device_b',
        ), 
   ]
