# Generated by Django 4.2.17 on 2025-06-24 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CONFIG_CONFIG_MODEL),
        ('sdwan_tunnel', '0016_remove_deviceb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicepeer',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='devicepeer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tunnel',
            name='device_b_subnet',
        ),
        migrations.RemoveField(
            model_name='tunnel',
            name='device_b_wan_ip',
        ),
        migrations.AddField(
            model_name='devicepeer',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.CONFIG_CONFIG_MODEL),
        ),
        migrations.AddField(
            model_name='devicepeer',
            name='subnet',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='devicepeer',
            name='wan_ip',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='device_b',
            field=models.ManyToManyField(blank=True, related_name='as_device_b', through='sdwan_tunnel.DevicePeer', to=settings.CONFIG_CONFIG_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='devicepeer',
            unique_together={('tunnel', 'device')},
        ),
        migrations.RemoveField(
            model_name='devicepeer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='devicepeer',
            name='link_subnet',
        ),
        migrations.RemoveField(
            model_name='devicepeer',
            name='local_device',
        ),
        migrations.RemoveField(
            model_name='devicepeer',
            name='local_ip',
        ),
        migrations.RemoveField(
            model_name='devicepeer',
            name='local_role',
        ),
        migrations.RemoveField(
            model_name='devicepeer',
            name='peer_device',
        ),
        migrations.RemoveField(
            model_name='devicepeer',
            name='peer_ip',
        ),
        migrations.RemoveField(
            model_name='devicepeer',
            name='peer_role',
        ),
    ]
