# Generated by Django 4.2.17 on 2025-05-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexapp_ipam', '0005_default_groups_permissions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ipaddress',
            table='openwisp_ipam_ipaddress',
        ),
        migrations.AlterModelTable(
            name='subnet',
            table='openwisp_ipam_subnet',
        ),
    ]
