# Generated by Django 4.2.17 on 2025-05-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan_tunnel', '0004_tunnel_device_b_subnet_tunnel_device_b_wan_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tunnel',
            name='template',
        ),
    ]
