# Generated by Django 4.2.17 on 2025-05-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan_tunnel', '0005_remove_tunnel_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='dpdaction',
            field=models.CharField(choices=[('restart', 'restart'), ('none', 'none')], default='none', help_text='Dead‐Peer Detection action (restart|none)', max_length=10),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='ipcomp',
            field=models.BooleanField(default=False, help_text='Enable IP compression'),
        ),
    ]
