# Generated by Django 4.2.17 on 2025-05-03 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CONFIG_CONFIG_MODEL),
        ('sdwan_tunnel', '0008_remove_tunnel_dpdaction_remove_tunnel_ipcomp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='dpdaction',
            field=models.CharField(choices=[('restart', 'restart'), ('none', 'none')], default='none', help_text='Dead‐Peer Detection action (restart|none)', max_length=10),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='ipcomp',
            field=models.BooleanField(default=False, help_text='Enable IP compression'),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='device_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_device_a', to=settings.CONFIG_CONFIG_MODEL),
        ),
    ]
