# Generated by Django 4.2.17 on 2025-05-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan_tunnel', '0010_alter_confighistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='last_config_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
