# Generated by Django 4.2.17 on 2025-05-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan_tunnel', '0011_tunnel_last_config_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('error', 'Error'), ('rolled_back', 'Rolled Back')], default='pending', max_length=16),
        ),
    ]
